name = "CSAWParallel"
uuid = "31cdde81-48f8-4e47-a8fc-cf890a92b930"
version = "1.0.0-DEV"
authors = ["Matthew Thomas <60493847+Syndrius@users.noreply.github.com> and contributors"]

[deps]
ChaoticShearAlfvenWaves = "864cfd1d-2a39-4b19-8808-16c25e50ed02"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PetscWrap = "5be22e1c-01b5-4697-96eb-ef9ccdc854b8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SlepcWrap = "c3679e3b-785e-4ccc-b734-b7685cbb935e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ChaoticShearAlfvenWaves = "1.0.0"
LinearAlgebra = "1.11.0"
julia = "1.10.3"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
