name = "MIDParallel"
uuid = "31cdde81-48f8-4e47-a8fc-cf890a92b930"
authors = ["Matthew Thomas <60493847+Syndrius@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
